server:
  port: 8080
spring:
  application:
    name: "empresa-computadores_upb3"
  datasource:
    url: jdbc:mysql://localhost:3306/computadores-upb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


